# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: CI (JS)

on:
  push:
    branches: [ "main" ]
    paths:
      - .github/workflows/ci-js.yml
      - src/js/**
      - .yarnrc.yml
      - package.json
      - tsconfig.json
      - vite.config.ts
      - yarn.lock

  pull_request:
    branches: [ "main" ]
    paths:
      - .github/workflows/ci-js.yml
      - src/js/**
      - .yarnrc.yml
      - package.json
      - tsconfig.json
      - vite.config.ts
      - yarn.lock

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 22
        cache: 'yarn'
    - run: yarn
    - run: yarn build
    - run: yarn test
